## 22 APRIL

Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.

In [44]:
import seaborn as sns 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder

In [45]:
from sklearn.datasets import load_iris

In [46]:
df=load_iris()

In [47]:
X=df.data

In [48]:
y=df.target

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [51]:
knn=KNeighborsClassifier(n_neighbors=5, algorithm='auto')

In [52]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [53]:
y_pred=knn.predict(X_test)

In [54]:
from sklearn.metrics import accuracy_score

In [55]:
print(accuracy_score(y_pred,y_test)*100,"%")

98.0 %


Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
sklearn.datasets.

In [278]:
from sklearn.datasets import fetch_openml
df= fetch_openml(name="house_prices", as_frame=True)

/opt/conda/lib/python3.10/site-packages/sklearn/datasets/_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [279]:
X=df.data
y=df.target

In [280]:
import pandas as pd

In [281]:
X=pd.DataFrame(X,columns=df.feature_names)
y=pd.DataFrame(y,columns=df.target_names)

In [282]:
X

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave  None      Reg   
1        2          20       RL         80.0     9600   Pave  None      Reg   
2        3          60       RL         68.0    11250   Pave  None      IR1   
3        4          70       RL         60.0     9550   Pave  None      IR1   
4        5          60       RL         84.0    14260   Pave  None      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave  None      Reg   
1456  1457          20       RL         85.0    13175   Pave  None      Reg   
1457  1458          70       RL         66.0     9042   Pave  None      Reg   
1458  1459          20       RL         68.0     9717   Pave  None      Reg   
1459  1460          20       RL         75.0     9937   Pave  None      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...           0        0   None   None   
1            Lvl    AllPub  ...           0        0   None   None   
2            Lvl    AllPub  ...           0        0   None   None   
3            Lvl    AllPub  ...           0        0   None   None   
4            Lvl    AllPub  ...           0        0   None   None   
...          ...       ...  ...         ...      ...    ...    ...   
1455         Lvl    AllPub  ...           0        0   None   None   
1456         Lvl    AllPub  ...           0        0   None  MnPrv   
1457         Lvl    AllPub  ...           0        0   None  GdPrv   
1458         Lvl    AllPub  ...           0        0   None   None   
1459         Lvl    AllPub  ...           0        0   None   None   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0           None       0      2    2008        WD         Normal  
1           None       0      5    2007        WD         Normal  
2           None       0      9    2008        WD         Normal  
3           None       0      2    2006        WD        Abnorml  
4           None       0     12    2008        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1455        None       0      8    2007        WD         Normal  
1456        None       0      2    2010        WD         Normal  
1457        Shed    2500      5    2010        WD         Normal  
1458        None       0      4    2010        WD         Normal  
1459        None       0      6    2008        WD         Normal  

[1460 rows x 80 columns]

In [283]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [284]:
from sklearn.preprocessing import LabelEncoder

In [285]:
lbl=LabelEncoder()

In [286]:
X["MSZoning"]=lbl.fit_transform(X["MSZoning"])
X["Street"]=lbl.fit_transform(X["Street"])
X["Alley"]=lbl.fit_transform(X["Alley"])
X["LotShape"]=lbl.fit_transform(X["LotShape"])
X["LandContour"]=lbl.fit_transform(X["LandContour"])
X["Utilities"]=lbl.fit_transform(X["Utilities"])
X["LotConfig"]=lbl.fit_transform(X["LotConfig"])
X["LandSlope"]=lbl.fit_transform(X["LandSlope"])
X["Neighborhood "]=lbl.fit_transform(X["Neighborhood"])
X["Condition1"]=lbl.fit_transform(X["Condition1"])
X["Condition2"]=lbl.fit_transform(X["Condition2"])
X["BldgType"]=lbl.fit_transform(X["BldgType"])
X["HouseStyle"]=lbl.fit_transform(X["HouseStyle"])
X["RoofStyle"]=lbl.fit_transform(X["RoofStyle"])
X["RoofMatl"]=lbl.fit_transform(X["RoofMatl"])
X["Exterior1st"]=lbl.fit_transform(X["Exterior1st"])
X["Exterior2nd"]=lbl.fit_transform(X["Exterior2nd"])
X["MasVnrType"]=lbl.fit_transform(X["MasVnrType"])
X["ExterQual"]=lbl.fit_transform(X["ExterQual"])
X["ExterCond"]=lbl.fit_transform(X["ExterCond"])
X["Foundation"]=lbl.fit_transform(X["Foundation"])
X["BsmtQual"]=lbl.fit_transform(X["BsmtQual"])
X["BsmtCond"]=lbl.fit_transform(X["BsmtCond"])
X["BsmtExposure"]=lbl.fit_transform(X["BsmtExposure"])
X["BsmtFinType1"]=lbl.fit_transform(X["BsmtFinType1"])
X["BsmtFinType2"]=lbl.fit_transform(X["BsmtFinType2"])
X["Heating"]=lbl.fit_transform(X["Heating"])
X["HeatingQC"]=lbl.fit_transform(X["HeatingQC"])
X["CentralAir"]=lbl.fit_transform(X["CentralAir"])
X["Electrical"]=lbl.fit_transform(X["Electrical"])
X["KitchenQual"]=lbl.fit_transform(X["KitchenQual"])
X["Functional"]=lbl.fit_transform(X["Functional"])
X["FireplaceQu"]=lbl.fit_transform(X["FireplaceQu"])
X["GarageType"]=lbl.fit_transform(X["GarageType"])
X["GarageFinish"]=lbl.fit_transform(X["GarageFinish"])
X["GarageQual"]=lbl.fit_transform(X["GarageQual"])
X["GarageCond"]=lbl.fit_transform(X["GarageCond"])
X["PavedDrive"]=lbl.fit_transform(X["PavedDrive"])
X["PoolQC"]=lbl.fit_transform(X["PoolQC"])
X["Fence"]=lbl.fit_transform(X["Fence"])
X["MiscFeature"]=lbl.fit_transform(X["MiscFeature"])
X["SaleType"]=lbl.fit_transform(X["SaleType"])
X["SaleCondition"]=lbl.fit_transform(X["SaleCondition"])

In [287]:
X.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
Neighborhood       0
Length: 81, dtype: int64

In [288]:
X["Saleprice"]=y

In [289]:
X=X.dropna().reset_index()

In [290]:
y=X["Saleprice"]

In [291]:
X=X.drop(["Saleprice","LotFrontage","MasVnrArea","GarageYrBlt"],axis=1)

In [292]:
from sklearn.model_selection import train_test_split

In [293]:
print(X.shape)
print(y.shape)


(1121, 79)
(1121,)


In [295]:
from sklearn.neighbors import KNeighborsRegressor

In [302]:
categorical_cols = X.select_dtypes(include=['object']).columns

In [303]:
X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [304]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.33, random_state=42)

In [306]:
knn = KNeighborsRegressor(n_neighbors=5, algorithm="auto")

In [307]:
knn.fit(X_train, y_train)

KNeighborsRegressor()

In [309]:
y=knn.predict(X_test)

In [311]:
from sklearn.metrics import r2_score

In [312]:
r2_score(y,y_test)

-0.0015013771577274682

Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

In [313]:
from sklearn.datasets import load_iris

In [315]:
import pandas as pd

In [316]:
df=load_iris()

In [324]:
X=pd.DataFrame(df.data,columns=df.feature_names)

In [326]:
y=df.target

In [ ]:
from sklearn.model_selection import train_test_split

In [334]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [335]:
from sklearn.neighbors import KNeighborsClassifier

In [336]:
knncl=KNeighborsClassifier()

In [337]:
from sklearn.model_selection import GridSearchCV

In [338]:
param={
"n_neighbors":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
}

In [339]:
clf=GridSearchCV(knncl,param_grid=param,cv=5,verbose=3,scoring="accuracy")

In [340]:
clf.fit(X_train,y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits
[CV 1/5] END .....................n_neighbors=1;, score=0.950 total time=   0.0s
[CV 2/5] END .....................n_neighbors=1;, score=0.900 total time=   0.0s
[CV 3/5] END .....................n_neighbors=1;, score=0.900 total time=   0.0s
[CV 4/5] END .....................n_neighbors=1;, score=1.000 total time=   0.0s
[CV 5/5] END .....................n_neighbors=1;, score=0.950 total time=   0.0s
[CV 1/5] END .....................n_neighbors=2;, score=0.900 total time=   0.0s
[CV 2/5] END .....................n_neighbors=2;, score=0.850 total time=   0.0s
[CV 3/5] END .....................n_neighbors=2;, score=0.900 total time=   0.0s
[CV 4/5] END .....................n_neighbors=2;, score=1.000 total time=   0.0s
[CV 5/5] END .....................n_neighbors=2;, score=0.950 total time=   0.0s
[CV 1/5] END .....................n_neighbors=3;, score=0.950 total time=   0.0s
[CV 2/5] END .....................n_neighbors=3;

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15]},
             scoring='accuracy', verbose=3)

In [341]:
clf.best_params_

{'n_neighbors': 1}

Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

In [342]:
from sklearn.datasets import fetch_openml
df= fetch_openml(name="house_prices", as_frame=True)

/opt/conda/lib/python3.10/site-packages/sklearn/datasets/_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [343]:
X=df.data
y=df.target

In [344]:
X=pd.DataFrame(X,columns=df.feature_names)
y=pd.DataFrame(y,columns=df.target_names)

In [345]:
X["Saleprice"]=y

In [346]:
df=X

In [347]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave  None      Reg   
1   2          20       RL         80.0     9600   Pave  None      Reg   
2   3          60       RL         68.0    11250   Pave  None      IR1   
3   4          70       RL         60.0     9550   Pave  None      IR1   
4   5          60       RL         84.0    14260   Pave  None      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0   None  None        None       0      2   
1         Lvl    AllPub  ...        0   None  None        None       0      5   
2         Lvl    AllPub  ...        0   None  None        None       0      9   
3         Lvl    AllPub  ...        0   None  None        None       0      2   
4         Lvl    AllPub  ...        0   None  None        None       0     12   

  YrSold  SaleType  SaleCondition  Saleprice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [350]:
categorical_cols = df.select_dtypes(include=['object']).columns

In [351]:
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [352]:
df.head()

Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0   1          60         65.0     8450            7            5       2003   
1   2          20         80.0     9600            6            8       1976   
2   3          60         68.0    11250            7            5       2001   
3   4          70         60.0     9550            7            5       1915   
4   5          60         84.0    14260            8            5       2000   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  SaleType_ConLI  SaleType_ConLw  \
0          2003       196.0         706  ...               0               0   
1          1976         0.0         978  ...               0               0   
2          2002       162.0         486  ...               0               0   
3          1970         0.0         216  ...               0               0   
4          2000       350.0         655  ...               0               0   

   SaleType_New  SaleType_Oth  SaleType_WD  SaleCondition_AdjLand  \
0             0             0            1                      0   
1             0             0            1                      0   
2             0             0            1                      0   
3             0             0            1                      0   
4             0             0            1                      0   

   SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                     0                     0                     1   
1                     0                     0                     1   
2                     0                     0                     1   
3                     0                     0                     0   
4                     0                     0                     1   

   SaleCondition_Partial  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0  

[5 rows x 247 columns]

In [355]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 247 entries, Id to SaleCondition_Partial
dtypes: float64(3), int64(35), uint8(209)
memory usage: 731.6 KB


In [356]:
df.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

       SaleType_ConLI  SaleType_ConLw  SaleType_New  SaleType_Oth  \
count     1460.000000     1460.000000   1460.000000   1460.000000   
mean         0.003425        0.003425      0.083562      0.002055   
std          0.058440        0.058440      0.276824      0.045299   
min          0.000000        0.000000      0.000000      0.000000   
25%          0.000000        0.000000      0.000000      0.000000   
50%          0.000000        0.000000      0.000000      0.000000   
75%          0.000000        0.000000      0.000000      0.000000   
max          1.000000        1.000000      1.000000      1.000000   

       SaleType_WD  SaleCondition_AdjLand  SaleCondition_Alloca  \
count  1460.000000            1460.000000           1460.000000   
mean      0.867808               0.002740              0.008219   
std       0.338815               0.052289              0.090317   
min       0.000000               0.000000              0.000000   
25%       1.000000               0.000000              0.000000   
50%       1.000000               0.000000              0.000000   
75%       1.000000               0.000000              0.000000   
max       1.000000               1.000000              1.000000   

       SaleCondition_Family  SaleCondition_Normal  SaleCondition_Partial  
count           1460.000000           1460.000000            1460.000000  
mean               0.013699              0.820548               0.085616  
std                0.116277              0.383862               0.279893  
min                0.000000              0.000000               0.000000  
25%                0.000000              1.000000               0.000000  
50%                0.000000              1.000000               0.000000  
75%                0.000000              1.000000               0.000000  
max                1.000000              1.000000               1.000000  

[8 rows x 247 columns]

Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

In [366]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [367]:
iris = load_iris()
X = iris.data
y = iris.target

In [368]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [369]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [371]:
k = 5  
weights = 'distance' 

In [372]:
knn_classifier = KNeighborsClassifier(n_neighbors=k, weights=weights)

In [373]:
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [374]:
y_pred = knn_classifier.predict(X_test)

In [375]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [376]:
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

In [378]:
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



Q6. Implement a function to standardise the features before applying KNN classifier.

In [380]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()


In [385]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [386]:
def standard(X_train,X_test,std):
    X_train=std.fit_transform(X_train)
    X_test=std.transform(X_test)
    
    return X_train,X_test

In [387]:
X_train,X_test=standard(X_train,X_test,std)

In [388]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)

In [389]:
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [390]:
y_pred = knn_classifier.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

In [391]:
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



Q7. Write a Python function to calculate the euclidean distance between two points.

In [361]:
import numpy as np

def euclidean_distance(point1, point2):
    point1 = np.array(point1)
    point2 = np.array(point2)
    distance = np.linalg.norm(point1 - point2)
    return distance


In [362]:
point1 = [1, 2, 3]
point2 = [4, 5, 6]

distance = euclidean_distance(point1, point2)
print("Euclidean Distance:", distance)


Euclidean Distance: 5.196152422706632


Q8. Write a Python function to calculate the manhattan distance between two points.

In [363]:
import numpy as np

def manhattan_distance(point1, point2):

    point1 = np.array(point1)
    point2 = np.array(point2)
    distance = np.sum(np.abs(point1 - point2))
    return distance


In [364]:
point1 = [1, 2, 3]
point2 = [4, 5, 6]

distance = manhattan_distance(point1, point2)
print("Manhattan Distance:", distance)


Manhattan Distance: 9
